/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.FBI;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.FBI;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.BudgetWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author imperio2494
 */
public class fbiFraudsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form fbiFraudsJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    public fbiFraudsJPanel(JPanel userProcessContainer,Organization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.organization=organization;
        populateTable();
        Color color = new Color(211, 247, 255);
        this.setBackground(color);
    }
    
    public void populateTable(){
    
    DefaultTableModel dtm = (DefaultTableModel)fbiFraudsTable.getModel();
        dtm.setRowCount(0);
   for (BudgetWorkRequest request : ((FBI)organization).getFrauds()){
       
            Object[] row = new Object[6];
            row[0] =  ((BudgetWorkRequest) request).getCertificate().getSenderOrganization();
            row[1]=request;
            row[2] = request.getDescription();
            row[3] = request.getStatus();
            int alloc = ((BudgetWorkRequest) request).getAllocatedBudgetRequest();
            row[4] = alloc;
            int total = ((BudgetWorkRequest) request).getTotalBudgetRequest();
            row[5] = total;
            
            dtm.addRow(row);
   }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fbiFraudsTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        fraudviewTable = new javax.swing.JTable();
        viewfraudBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setText("Frauds");

        fbiFraudsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "organization", "message", "description", "requested budget", "allocated budget", "status"
            }
        ));
        jScrollPane1.setViewportView(fbiFraudsTable);

        fraudviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "attribute", "value"
            }
        ));
        jScrollPane2.setViewportView(fraudviewTable);

        viewfraudBtn.setText("view");
        viewfraudBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewfraudBtnActionPerformed(evt);
            }
        });

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewfraudBtn)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewfraudBtn)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewfraudBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewfraudBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = fbiFraudsTable.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        BudgetWorkRequest workrequest= (BudgetWorkRequest)fbiFraudsTable.getValueAt(selectedRow, 1);

        DefaultTableModel dtm = (DefaultTableModel)fraudviewTable.getModel();
        dtm.setRowCount(0); 
        dtm.addRow(new Object[]{"senderOrganization",workrequest.getCertificate().getSenderOrganization()});
        dtm.addRow(new Object[]{"message",workrequest});
        dtm.addRow(new Object[]{"description",workrequest.getDescription()});
        dtm.addRow(new Object[]{"sender",workrequest.getSender()});
        dtm.addRow(new Object[]{"receiver",workrequest.getReceiver()});
        dtm.addRow(new Object[]{"requestdate",workrequest.getRequestDate().toString()});
        dtm.addRow(new Object[]{"resolvedate",(workrequest.getResolveDate()!=null)?workrequest.getResolveDate().toString():null});
        dtm.addRow(new Object[]{"requestedbudget",workrequest.getTotalBudgetRequest()});
        dtm.addRow(new Object[]{"allocatedbudget",workrequest.getAllocatedBudgetRequest()});
        dtm.addRow(new Object[]{"reports",workrequest.getCertificate().getReports()});
        dtm.addRow(new Object[]{"status",workrequest.getStatus()});
    }//GEN-LAST:event_viewfraudBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        fbiOrgWorkAreaJPanel dwjp = (fbiOrgWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable fbiFraudsTable;
    private javax.swing.JTable fraudviewTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton viewfraudBtn;
    // End of variables declaration//GEN-END:variables
}
