/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.FBI;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FBI;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BudgetWorkRequest;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author imperio2494
 */
public class fbiViewDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form fbiViewDetailsJPanel
     */
    private JPanel userProcessContainer;
    private BudgetWorkRequest workrequest;
    private UserAccount account;
    private Network network;
    private Enterprise enterprise;
    public fbiViewDetailsJPanel(JPanel userProcessContainer,BudgetWorkRequest workrequest,UserAccount account,Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.workrequest=workrequest;
        this.account=account;
        this.enterprise=enterprise;
        this.network=network;
        populateTable();
        
        if(workrequest.getCertificate().getReports()!=null)
        {
        ReportsTable.setVisible(true);
        populateReportTable(workrequest.getCertificate().getReports());
        }
        else
            ReportsTable.setVisible(false);
    }
    
    public void populateReportTable(String filepath){
        ReportsTable.setAutoResizeMode(4);
    DefaultTableModel dtm = (DefaultTableModel)ReportsTable.getModel();
    dtm.setRowCount(0);
    
    try (BufferedReader br = new BufferedReader(new FileReader(filepath))) {
        String line;
//        ReportsTable 
        boolean columnnames=false;
        while ((line = br.readLine()) != null){
            String[] values = line.split(",");
            if(!columnnames){
//            dtm.setColumnCount(values.length);
             columnnames=true;
            }
            else{
               dtm.addRow(new Object[]{values[0],values[1]});
                
            }
            
        }
    
    }catch(Exception e){}
//    dtm.setColumnCount(SOMEBITS);
    
    }
    
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)fbiviewdetailsTable.getModel();
        dtm.setRowCount(0); 
        dtm.addRow(new Object[]{"senderOrganization",workrequest.getCertificate().getSenderOrganization()});
        dtm.addRow(new Object[]{"message",workrequest});
        dtm.addRow(new Object[]{"description",workrequest.getDescription()});
        dtm.addRow(new Object[]{"sender",workrequest.getSender()});
        dtm.addRow(new Object[]{"receiver",workrequest.getReceiver()});
        dtm.addRow(new Object[]{"requestdate",workrequest.getRequestDate().toString()});
        dtm.addRow(new Object[]{"resolvedate",(workrequest.getResolveDate()!=null)?workrequest.getResolveDate().toString():null});
        dtm.addRow(new Object[]{"requestedbudget",workrequest.getTotalBudgetRequest()});
        dtm.addRow(new Object[]{"allocatedbudget",workrequest.getAllocatedBudgetRequest()});
        dtm.addRow(new Object[]{"reports",workrequest.getCertificate().getReports()});
        dtm.addRow(new Object[]{"status",workrequest.getStatus()});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fbiviewdetailsTable = new javax.swing.JTable();
        fraudBtn = new javax.swing.JButton();
        transpBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReportsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        fbiviewdetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "attribute ", "value"
            }
        ));
        jScrollPane1.setViewportView(fbiviewdetailsTable);

        fraudBtn.setText("Fraud");
        fraudBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fraudBtnActionPerformed(evt);
            }
        });

        transpBtn.setText("Transparant");
        transpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transpBtnActionPerformed(evt);
            }
        });

        ReportsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Message", "Amount"
            }
        ));
        jScrollPane2.setViewportView(ReportsTable);

        jLabel1.setText("REPORTS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(fraudBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transpBtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fraudBtn)
                    .addComponent(transpBtn))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fraudBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fraudBtnActionPerformed
        // TODO add your handling code here:
        FBI organ=null;
        for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
            for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList()){
                   if(org instanceof FBI)
                   organ=(FBI)org;
                   if(organ!=null)
                       break;   
                   }
            
        if(organ!=null)
           break;  
        }
        workrequest.getCertificate().setIsFraud(true);
        if(organ!=null)
              organ.getFrauds().add(workrequest);
        account.getWorkQueue().getWorkRequestList().remove(workrequest);
    }//GEN-LAST:event_fraudBtnActionPerformed

    private void transpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transpBtnActionPerformed
        // TODO add your handling code here:
        account.getWorkQueue().getWorkRequestList().remove(workrequest);
        workrequest.setStatus("add to certificate");
    }//GEN-LAST:event_transpBtnActionPerformed
        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ReportsTable;
    private javax.swing.JTable fbiviewdetailsTable;
    private javax.swing.JButton fraudBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton transpBtn;
    // End of variables declaration//GEN-END:variables
}
