/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Certificate;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FBI;
import Business.Organization.Organization;
import javax.swing.JPanel;
import Business.WorkQueue.BudgetWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import Business.UserAccount.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imperio2494
 */
public class certificateViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form certificateViewJPanel
     */
    private JPanel userProcessContainer;
    private BudgetWorkRequest workrequest;
    private UserAccount account;
    private Network network;
    private Enterprise enterprise;
    public certificateViewJPanel(JPanel userProcessContainer,BudgetWorkRequest workrequest,UserAccount account,Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.workrequest=workrequest;
        this.account=account;
        this.enterprise=enterprise;
        this.network=network;
        populateWorkrequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void populateWorkrequest(){
        DefaultTableModel dtm = (DefaultTableModel)certificateworkrequestTable.getModel();
        dtm.setRowCount(0); 
        dtm.addRow(new Object[]{"senderOrganization",workrequest.getCertificate().getSenderOrganization()});
        dtm.addRow(new Object[]{"message",workrequest});
        dtm.addRow(new Object[]{"description",workrequest.getDescription()});
        dtm.addRow(new Object[]{"sender",workrequest.getSender()});
        dtm.addRow(new Object[]{"receiver",workrequest.getReceiver()});
        dtm.addRow(new Object[]{"requestdate",workrequest.getRequestDate().toString()});
        dtm.addRow(new Object[]{"resolvedate",(workrequest.getResolveDate()!=null)?workrequest.getResolveDate().toString():null});
        dtm.addRow(new Object[]{"requestedbudget",workrequest.getTotalBudgetRequest()});
        dtm.addRow(new Object[]{"allocatedbudget",workrequest.getAllocatedBudgetRequest()});
        dtm.addRow(new Object[]{"reports",workrequest.getCertificate().getReports()});
        dtm.addRow(new Object[]{"status",workrequest.getStatus()});
        
        
        
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        certificateworkrequestTable = new javax.swing.JTable();
        investigate = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        addToCertificateBtn = new javax.swing.JButton();

        certificateworkrequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "attribute", "value"
            }
        ));
        jScrollPane1.setViewportView(certificateworkrequestTable);

        investigate.setText("send to investigate");
        investigate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investigateActionPerformed(evt);
            }
        });

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addToCertificateBtn.setText("addtocertificate");
        addToCertificateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCertificateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(investigate)
                .addGap(28, 28, 28)
                .addComponent(addToCertificateBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(260, 260, 260))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(investigate)
                    .addComponent(addToCertificateBtn))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        certificateUserWorkAreaJPanel dwjp = (certificateUserWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addToCertificateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCertificateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToCertificateBtnActionPerformed

    private void investigateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investigateActionPerformed
        // TODO add your handling code here:
        
        
        String message = workrequest.getMessage();
        String description = workrequest.getDescription();
        int totalFundRequest = workrequest.getTotalBudgetRequest();
        String Status=workrequest.getStatus();
        int AllocatedBudget=workrequest.getAllocatedBudgetRequest();
        
        BudgetWorkRequest request = new BudgetWorkRequest();
        
        request.setMessage(message);
        request.setDescription(description);
        request.setTotalBudgetRequest(totalFundRequest);
        request.setSender(account);
        request.setStatus("Sent");
        
        Organization org = null;
        for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
            for(Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof FBI){
                    org = organization;
                    break;
                }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
    }//GEN-LAST:event_investigateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCertificateBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable certificateworkrequestTable;
    private javax.swing.JButton investigate;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
