/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Reports;

import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;


/**
 *
 * @author imperio2494
 */
public class ReportTypeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private EcoSystem system;
    JPanel userProcessContainer;
    public ReportTypeJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.system=system;
        this.userProcessContainer=userProcessContainer;
        Color color = new Color(211, 247, 255);
        this.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CertificatesBtn = new javax.swing.JButton();
        AnalyticsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        CertificatesBtn.setText("Certificates");
        CertificatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CertificatesBtnActionPerformed(evt);
            }
        });

        AnalyticsBtn.setText("Analytics");
        AnalyticsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AnalyticsBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CertificatesBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(CertificatesBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backBtn)))
                .addGap(18, 18, 18)
                .addComponent(AnalyticsBtn)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AnalyticsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("Graphs",new ReportsJPanel(userProcessContainer,system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AnalyticsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void CertificatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CertificatesBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("Certificates",new certificatesJPanel(userProcessContainer,system));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_CertificatesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyticsBtn;
    private javax.swing.JButton CertificatesBtn;
    private javax.swing.JButton backBtn;
    // End of variables declaration//GEN-END:variables
}
