/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Budget;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ArmyOrganization;
import Business.Organization.BudgetOrganization;
import Business.Organization.BureauOfEconomicAnalysisOrganization;
import Business.Organization.CertificateOrganization;
import Business.Organization.Organization;
import Business.Organization.RevenueOrganization;
import Business.Role.certificateOrgRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BudgetWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.certificateWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.Army.createBudgetRequest;

/**
 *
 * @author Preetham Reddy
 */
public class BudgetWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form budgetPanel
     */
    
    private JPanel userProcessContainer;
    private BudgetOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    public BudgetWorkAreaPanel(JPanel userProcessContainer, UserAccount account, BudgetOrganization organization,  Enterprise enterprise, Network network) {
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network=network;
        initComponents();
        populateTable();
        valueLabel.setText(this.enterprise.getName());
        try{
        ImageIcon iconLogo = new ImageIcon(Paths.get("imgs/budget.png").toAbsolutePath().toString());
        ImgLable.setIcon(new ImageIcon(iconLogo.getImage().getScaledInstance(300, 80, Image.SCALE_DEFAULT)));

        }
        catch(Exception e){}
        Color color = new Color(211, 247, 255);
        this.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        assignButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BudetTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        certificateButton = new javax.swing.JButton();
        revenueButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        ImgLable = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Budget Panel");

        assignButton.setText("assign to me");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });

        BudetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "messgae", "description", "budget request", "allocated budget", "status", "Reciver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BudetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BudetTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BudetTable);

        jButton2.setText("get approval from Commerce");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        certificateButton.setText("get approval from certifiacte");
        certificateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificateButtonActionPerformed(evt);
            }
        });

        revenueButton.setText("get approval from revenue");
        revenueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(assignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(certificateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(revenueButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                                .addComponent(ImgLable, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addComponent(ImgLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignButton)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(revenueButton)
                .addGap(18, 18, 18)
                .addComponent(certificateButton)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void populateTable(){
        
        DefaultTableModel dtm = (DefaultTableModel)BudetTable.getModel();
        dtm.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getDescription();
            row[4] = request.getStatus();
            double alloc = ((BudgetWorkRequest) request).getAllocatedBudgetRequest();
            row[3] = alloc;
            int total = ((BudgetWorkRequest) request).getTotalBudgetRequest();
            row[2] = total;
            row[5] = request.getReceiver();
            
            dtm.addRow(row);
        }
        
    }
    
    
    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        int selectedRow = BudetTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select a row"); 
            return;
        }
        
        WorkRequest request = (WorkRequest)BudetTable.getValueAt(selectedRow, 0);
        request.setReceiver(userAccount);
        JOptionPane.showMessageDialog(null, "Task assigned Sucessfully ");
        populateTable();
        
        
        
    }//GEN-LAST:event_assignButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = BudetTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select a row"); 
            return;
        }
        
        
        
        WorkRequest request = (WorkRequest)BudetTable.getValueAt(selectedRow, 0);
        Organization org = null;
        
        String test = request.getStatus();
        if( test.equals("Bureau of Ecomonics Approved")|| test.equals("Revenue Approved")){
            if(test.equals("Revenue Approved")){
                JOptionPane.showMessageDialog(null, "Request already approved by Bureau of Ecomonics and Revenue");
                return;
            }
            JOptionPane.showMessageDialog(null, "Request already approved by Bureau of Ecomonics");
            return;
            
        }
        
        for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
            for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof BureauOfEconomicAnalysisOrganization){
                    org = organization;
                    break;
                }
            }
        }
        if (org!=null){
//            request.setSenderOrganization();
            org.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request Sucessfully placed"); 
            //CertificateOrganization.getWorkQueue().getWorkRequestList().add(request);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void certificateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificateButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = BudetTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select a row"); 
            return;
        }
        
        WorkRequest request = (WorkRequest)BudetTable.getValueAt(selectedRow, 0);
        Organization org = null;
        String test = request.getStatus();
        if(!test.equals("Revenue Approved")){
            System.out.println(request.getStatus());
            JOptionPane.showMessageDialog(null, "get approval from revenue first");
            return;
            
        }
        
        
        for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
            for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof CertificateOrganization){
                    org = organization;
                    break;
                }
            }
        }
        if (org!=null){
//            request.setSenderOrganization();
            org.getWorkQueue().getWorkRequestList().add(request);
            //CertificateOrganization.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request Sucessfully placed");
        }
    }//GEN-LAST:event_certificateButtonActionPerformed

    private void revenueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = BudetTable.getSelectedRow();
        
        
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select a row"); 
            return;
        }
        
        WorkRequest request = (WorkRequest)BudetTable.getValueAt(selectedRow, 0);
        Organization org = null;
        
        String test = request.getStatus();
        System.out.println(test);
        if( test.equals("Revenue Approved")){
            JOptionPane.showMessageDialog(null, "Request already approved by revenue");
            return;
            
        }
        if( !test.equals("Bureau of Ecomonics Approved")){
            JOptionPane.showMessageDialog(null, "get approval from commerce first");
            return;
            
        }
        
        for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
            for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof RevenueOrganization){
                    org = organization;
                    break;
                }
            }
        }
       
        
        if (org!=null){
//            request.setSenderOrganization();
            org.getWorkQueue().getWorkRequestList().add(request);
            //CertificateOrganization.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request Sucessfully placed");
        }
    }//GEN-LAST:event_revenueButtonActionPerformed

    private void BudetTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BudetTableMouseClicked
         int selectedRow = BudetTable.getSelectedRow();
        
         if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Select a row"); 
            return;
        }
        
        
        WorkRequest request = (WorkRequest)BudetTable.getValueAt(selectedRow, 0);
        String test = request.getStatus();
        certificateButton.setEnabled(false);
        revenueButton.setEnabled(false);
        jButton2.setEnabled(true);
        if(test.equals("Revenue Approved")){
            certificateButton.setEnabled(true);
            jButton2.setEnabled(false);
            return;
            
        }
        else if(test.equals("Bureau of Ecomonics Approved")){
            revenueButton.setEnabled(true);
            jButton2.setEnabled(false);
            return;
            
        }
    }//GEN-LAST:event_BudetTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BudetTable;
    private javax.swing.JLabel ImgLable;
    private javax.swing.JButton assignButton;
    private javax.swing.JButton certificateButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton revenueButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
